/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
/**
 *
 * @author kouts
 */
public class CreateNewArticle extends javax.swing.JFrame {
    
    // private JTextField jTextField5;
    
    public void setUser(String user) {this.jTextField5.setText(user);}
    public String getUser() {return this.jTextField5.getText();}


    public static Connection getConnection(){
     
        Connection con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db", "root", "pass123");
        } catch (Exception ex) {
            System.out.println("here1");
            System.out.println(ex.getMessage());
        }
        
        return con;
    }
    
    
    /**
     * Creates new form Journalist_CreateNewArticle
     */
    public CreateNewArticle() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        article = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Create New Article");

        jLabel2.setText("Specify the exact Path*:");

        jLabel3.setText("Give a short summary of the article*:");

        jLabel4.setText("Article's Category*:");

        jLabel5.setText("Article's Title* :");

        jLabel6.setText("Additional Journalists:");

        jLabel7.setText("Keywords:");

        jLabel8.setText("Pages*:");

        jLabel9.setText("Images:");

        article.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                articleMouseClicked(evt);
            }
        });
        article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CREATE");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 51, 51));
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Fields with * must be filled!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(article)
                                .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                .addComponent(jTextField6)
                                .addComponent(jTextField5)
                                .addComponent(jTextField4)
                                .addComponent(jTextField3)
                                .addComponent(jTextField2)))))
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(article, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTextField2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextField4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jTextField5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1))
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_articleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String atitle = article.getText();
        String apath = jTextField2.getText();
        String asummary = jTextField3.getText();
        Integer acategory = Integer.parseInt(jTextField4.getText());
        String ajournalist = jTextField5.getText();
        String akeyword = jTextField6.getText();
        Integer apages = Integer.parseInt(jTextField7.getText());
        // Date firstDate = new Date();
        LocalDate localDate = LocalDate.now();
        java.sql.Date date = java.sql.Date.valueOf(localDate);
        
        // SHMEIWSH THEWROUME OTI MPOREI ARTICLE NA EXEI TON IDIO TITLO ALLA ENNOEITAI DIAFORETIKO PATH ! 
        
        if(verifyFields())
        {
            if(!checkPath(apath))
            {
                if(!checkJourn(ajournalist))
                {
                   if(!checkCategory(acategory))
                    {
                        PreparedStatement ps;
                        PreparedStatement ps2;
                        PreparedStatement ps3;
                        ResultSet rs;
                        String createArticleQuery = "INSERT INTO `ARTICLE` VALUES (?, ?, ?, ?, ?)";
                        String createArticleQuery2 = "INSERT INTO `SUBMISSION` VALUES (?, ?, ?)";
                        String createArticleQuery3 = "INSERT INTO `KEYWORDS` VALUES (?, ?)";
                        
                        // System.out.println("hello");
                        
                        try {
                        ps = CreateNewArticle.getConnection().prepareStatement(createArticleQuery);
                        ps2 = CreateNewArticle.getConnection().prepareStatement(createArticleQuery2);
                        ps3 = CreateNewArticle.getConnection().prepareStatement(createArticleQuery3);
                        ps.setString(1, apath);
                        ps.setString(2, atitle);
                        ps.setString(3, asummary);
                        ps.setInt(4, apages);
                        ps.setInt(5, acategory);
                        ps2.setString(2, apath);
                        ps2.setString(1,LoginFrame.email);
                        ps2.setDate(3, date);
                        ps3.setString(1, apath);
                        ps3.setString(2, akeyword);
                        
                        if(ps.executeUpdate() != 0)
                        {
                            JOptionPane.showMessageDialog(null, "Your article has been created");
                        }else{JOptionPane.showMessageDialog(null, "ERROR");}
                        
                        } catch (SQLException ex) {
                            System.out.println(ex.getMessage());
                            System.out.println("here1");
                        }
                    }
                }
               }
            }// TODO add your handling code here:
        }//GEN-LAST:event_jButton2MouseClicked
    public boolean verifyFields()
    {
        String atitle = article.getText();
        String apath = jTextField2.getText();
        String asummary = jTextField3.getText();
        Integer acategory = Integer.parseInt(jTextField4.getText());
        String ajournalist = jTextField5.getText();
        String akeyword = jTextField6.getText();
        Integer apages = Integer.parseInt(jTextField7.getText());
        
        if(atitle.trim().equals("") || apath.trim().equals("") || asummary.trim().equals("")
           || acategory.equals("") || apages.equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or more Fields are empty");
            return false;
        }    
        
        return true;    
    }
    
    public boolean checkPath(String apath)
    {
        /*String atitle = article.getText();
        String apath = jTextField2.getText();
        String asummary = jTextField3.getText();
        Integer acategory = Integer.parseInt(jTextField4.getText());
        String ajournalist = jTextField5.getText();
        String akeyword = jTextField6.getText();
        Integer apages = Integer.parseInt(jTextField7.getText());*/
        
        PreparedStatement ps;
        ResultSet rs;
        boolean path_exist = false;
        
        String query = "SELECT * FROM `ARTICLE` WHERE `art_path` =?";
        
        try {
            ps = CreateNewArticle.getConnection().prepareStatement(query);
            ps.setString(1, apath);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                path_exist = true;
                JOptionPane.showMessageDialog(null, "This article already exists");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            System.out.println("here2");
        }
        
        return path_exist;
    }
    
    public boolean checkJourn(String ajournalist)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean journ_exist = false;
        
        String query = "SELECT * FROM `JOURNALIST` WHERE `journal_email` = ?";
        
        try {
            ps = CreateNewArticle.getConnection().prepareStatement(query);
            ps.setString(1, ajournalist);
            
            rs = ps.executeQuery();
            
            if(!rs.next() && ajournalist.length()>5)
            {
                journ_exist = true;
                JOptionPane.showMessageDialog(null, "The journalist doesn't exists");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            System.out.println("here3");
        }
        
        return journ_exist;
    }

     public boolean checkCategory(Integer acategory)
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean category_exist = false;
        
        String query = "SELECT * FROM `CATEGORY` WHERE `id` =?";
        
        try {
            ps = CreateNewArticle.getConnection().prepareStatement(query);
            ps.setInt(1, acategory);
            
            rs = ps.executeQuery();
            
            if(!rs.next())
            {
                category_exist = true;
                JOptionPane.showMessageDialog(null, "The category doesn't exist");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            System.out.println("here4");
        }
        
        return category_exist;
    }
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void articleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_articleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_articleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNewArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNewArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNewArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNewArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNewArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField article;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}

                        
                        
