/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author makis
 */
public class Editor_AcceptArticle extends javax.swing.JFrame {

    /**
     * Creates new form AcceptArticle
     */
    public Editor_AcceptArticle() {
        initComponents();
        FillCombo();
        jTextField1.setText(LoginFrame.email);
        setLocationRelativeTo(null);
    
    Statement stmt =null;
        try {
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project_db","root","pass123");           
            stmt = conn.createStatement();
            String query = "select * from submission";

            ResultSet rs = stmt.executeQuery(query);

            rs.beforeFirst();
               
            String[] columnNames = {"JOURNALIST", "PATH", "SUBMISSION DATE"};
            DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);
            while (rs.next()) {
                String journ = rs.getString("journalist");
                String art = rs.getString("article");
                String sub = rs.getString("sub_date");             

                // create a single array of one row's worth of data
                String[] data = { journ,art,sub} ;

                // and add this row of data into the table model
                tableModel.addRow(data);
                
            }
            jTable1.setModel(tableModel);

           /*jTable1.setPreferredScrollableViewportSize(new Dimension(1600, 400));
            jTable1.setFillsViewportHeight(true);*/

        }
        catch (Exception er) {System.err.println(er);}
    }


    private void FillCombo(){
        PreparedStatement ps;
        ResultSet rs;
       try{
            String sql="select * from submission";
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project_db","root","pass123");           
            ps = conn.prepareStatement(sql);
            rs=ps.executeQuery();
            
            while(rs.next()){
               String name = rs.getString("article");
               jComboBox1.addItem(name);
            }
       
       }catch(Exception e){JOptionPane.showMessageDialog (null, e);} 
       jComboBox1.addItem("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        comboOne = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "JOURNALIST", "PATH", "SUBMISSION DATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(5);
        }

        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("CHIEF");

        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("COMMENTS");

        comboOne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACCEPT", "REJECT", "RETYPE" }));
        comboOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboOneMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("SUBMIT CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("ARTICLE CHECKING");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(comboOne, 0, 187, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(322, 322, 322))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboOneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboOneMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String chief = jTextField1.getText();
        String path = (String)jComboBox1.getSelectedItem( );
        String comments = jTextField3.getText();
        String status = (String)comboOne.getSelectedItem( );
        LocalDate localDate = LocalDate.now();
        Date date = Date.valueOf(localDate);
        
        PreparedStatement stmt;
        try {
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project_db","root","pass123");          
            String query = "insert into CHECKING values (?,?,?,?,?)";
            stmt = conn.prepareStatement(query);
            if(verifyFields())
            {System.out.println("helloif1"); 
                if(checkPath(path))
                {System.out.println("hello3if2");
                    if(!checkJourn(chief)) 
                    {System.out.println("hello3if3");    
                        try{    
                            stmt.setDate(5, date);
                            stmt.setString(1, chief);
                            stmt.setString(2, path);
                            stmt.setString(3, comments);
                            stmt.setString(4, status);
                            System.out.println("hello3");
                            stmt.executeUpdate();    

                            if(stmt.executeUpdate() != 0 )
                            {
                                JOptionPane.showMessageDialog(null, "Your article has been updated");
                            }else{JOptionPane.showMessageDialog(null, "ERROR");}
                        } 
                        catch (SQLException ex) {
                            System.out.println(ex.getMessage());
                        }
                    }
                }
            }
        }    
    catch (Exception e)
        {
          System.err.println("Got an exception! ");
          System.err.println(e.getMessage());
        }
            // TODO add your handling code here:                                                     
    }//GEN-LAST:event_jButton1ActionPerformed

        public boolean verifyFields()
    {
        String atitle = (String)jComboBox1.getSelectedItem( );
        String apath = jTextField1.getText();    
        if(atitle.trim().equals("") || apath.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "PATH or CHIEF is empty");
            return false;
        }    
        
        return true;    
    }
    
    public boolean checkPath(String apath)
    {    
        PreparedStatement ps;
        ResultSet rs;
        String path = apath;
        boolean path_exist = false;
        
        String query = "SELECT * FROM SUBMISSION WHERE article = ?";
        
        try {
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project_db","root","pass123");           
            ps = conn.prepareStatement(query);
            ps.setString(1, path);
            rs = ps.executeQuery();
            if(rs.next())
            {
                path_exist = true;
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        return path_exist;
    }
    
    public boolean checkJourn(String ajournalist)
    {
        PreparedStatement ps;
        ResultSet rs;
        String journ = ajournalist;
        boolean journ_exist = false;
        
        String query = "SELECT * FROM newspaper WHERE editor_in_chief = ? ";
        
        try {
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost/project_db","root","pass123");           
            ps = conn.prepareStatement(query);            
            ps.setString(1, journ);
            System.out.println("checkJourn");
            rs = ps.executeQuery();
            
            if(!rs.next())
            {
                journ_exist = true;
                JOptionPane.showMessageDialog(null, "The chief doesn't exists");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            System.out.println("here3");
        }
        
        return journ_exist;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor_AcceptArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor_AcceptArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor_AcceptArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor_AcceptArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor_AcceptArticle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboOne;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}

