/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.lang.Exception;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author makis
 */
public class Editor_CreateCategory extends javax.swing.JFrame {

    /**
     * Creates new form CategoryCreate
     */
    public Editor_CreateCategory() {
        initComponents();
        setLocationRelativeTo(null);
        FillCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 51, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 51, 0), new java.awt.Color(153, 0, 0)));

        jTextField3.setBackground(new java.awt.Color(132, 0, 0));
        jTextField3.setForeground(new java.awt.Color(255, 0, 0));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("CATEGORY NAME");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("CREATE");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setText("CATEGORY CREATION");

        jComboBox1.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(255, 0, 0));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PARENTAL CATEGORY");

        jTextField4.setBackground(new java.awt.Color(132, 0, 0));
        jTextField4.setForeground(new java.awt.Color(255, 0, 0));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("DESCRIPTION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Integer idx = 0;
    String parent = (String)jComboBox1.getSelectedItem( ); 
    String name = jTextField3.getText();
    String des = jTextField4.getText();
    PreparedStatement stmt;
    try {
        Connection conn;
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root", "pass123");          
        String query = "insert into category(`id`,`parent_id`,`name_category`,`description`) values (?,?,?,?)";
        stmt = conn.prepareStatement(query);        
            if(parent.trim().equals("") && verifyFields() && checkName(name))
            {System.err.println("Got an exception! ");
                    try{
                    stmt.setNull(1,idx);
                    stmt.setNull(2, idx);
                    stmt.setString(3, name);
                    stmt.setString(4, des);
                      
                        if(stmt.executeUpdate() != 0 )
                        {
                            JOptionPane.showMessageDialog(null, "Your category has been created");
                        }else{JOptionPane.showMessageDialog(null, "ERROR");}
                    } 
                    catch (SQLException ex) {
                            System.out.println(ex.getMessage());
                    }
            }
            else if(!parent.trim().equals(null) && verifyFields() && checkName(name))
            {      
                    try{
                    Integer parid = checkCategory(parent);
                    stmt.setNull(1,idx);
                    stmt.setInt(2, parid);
                    stmt.setString(3, name);
                    stmt.setString(4, des);
                       
                        if(stmt.executeUpdate() != 0 )
                        {
                            JOptionPane.showMessageDialog(null, "Your category has been created");
                        }else{JOptionPane.showMessageDialog(null, "ERROR");}
                    } 
                    catch (SQLException ex) {
                            System.out.println(ex.getMessage());
                    }
            }
    }    
    catch (Exception e)
        {
          System.err.println("Got an exception! ");
          System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public int checkCategory(String parent)
    {
        PreparedStatement ps;
        ResultSet rs;
        Integer category_exist = null;
        
        String query = "SELECT id FROM CATEGORY WHERE name_category =?";
        
        try {
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root", "pass123");           
            ps = conn.prepareStatement(query);            
            ps.setString(1, parent);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                category_exist = rs.getInt("id");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        return category_exist;
    }
    
    public boolean checkName(String name)
    {    
        PreparedStatement ps;
        ResultSet rs;
        String path = name;
        boolean path_exist = true;
        
        String query = "SELECT * FROM category WHERE name_category = ?";
        
        try {
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root", "pass123");           
            ps = conn.prepareStatement(query);
            ps.setString(1, path);
            rs = ps.executeQuery();
            if(rs.next())
            {
                path_exist = false;
                JOptionPane.showMessageDialog(null, "Category already exists");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        
        return path_exist;
    }
    
    public boolean verifyFields()
    {
        String asummary = jTextField3.getText();
        String apages = jTextField4.getText();
        
        if(asummary.trim().equals("") || apages.equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or more Fields are empty");
            return false;
        }    
        
        return true;    
    }
    
    private void FillCombo(){
        PreparedStatement ps;
        ResultSet rs;
       try{
            String sql="select name_category from category";
            Connection conn;
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project_db","root", "pass123");           
            ps = conn.prepareStatement(sql);
            rs=ps.executeQuery();
            
            while(rs.next()){
               String name = rs.getString("name_category");
               jComboBox1.addItem(name);
            }
       
       }catch(Exception e){JOptionPane.showMessageDialog (null, e);} 
       jComboBox1.addItem("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor_CreateCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor_CreateCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor_CreateCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor_CreateCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor_CreateCategory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
